/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesUndergraduateRouteImport } from './routes/services.undergraduate'
import { Route as ServicesBoardingSchoolsRouteImport } from './routes/services.boarding-schools'
import { Route as ServicesAthleticRecruitmentRouteImport } from './routes/services.athletic-recruitment'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesUndergraduateRoute = ServicesUndergraduateRouteImport.update({
  id: '/services/undergraduate',
  path: '/services/undergraduate',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBoardingSchoolsRoute = ServicesBoardingSchoolsRouteImport.update({
  id: '/services/boarding-schools',
  path: '/services/boarding-schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAthleticRecruitmentRoute =
  ServicesAthleticRecruitmentRouteImport.update({
    id: '/services/athletic-recruitment',
    path: '/services/athletic-recruitment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/athletic-recruitment': typeof ServicesAthleticRecruitmentRoute
  '/services/boarding-schools': typeof ServicesBoardingSchoolsRoute
  '/services/undergraduate': typeof ServicesUndergraduateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/athletic-recruitment': typeof ServicesAthleticRecruitmentRoute
  '/services/boarding-schools': typeof ServicesBoardingSchoolsRoute
  '/services/undergraduate': typeof ServicesUndergraduateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/athletic-recruitment': typeof ServicesAthleticRecruitmentRoute
  '/services/boarding-schools': typeof ServicesBoardingSchoolsRoute
  '/services/undergraduate': typeof ServicesUndergraduateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/services/athletic-recruitment'
    | '/services/boarding-schools'
    | '/services/undergraduate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/services/athletic-recruitment'
    | '/services/boarding-schools'
    | '/services/undergraduate'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/services/athletic-recruitment'
    | '/services/boarding-schools'
    | '/services/undergraduate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesAthleticRecruitmentRoute: typeof ServicesAthleticRecruitmentRoute
  ServicesBoardingSchoolsRoute: typeof ServicesBoardingSchoolsRoute
  ServicesUndergraduateRoute: typeof ServicesUndergraduateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/undergraduate': {
      id: '/services/undergraduate'
      path: '/services/undergraduate'
      fullPath: '/services/undergraduate'
      preLoaderRoute: typeof ServicesUndergraduateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/boarding-schools': {
      id: '/services/boarding-schools'
      path: '/services/boarding-schools'
      fullPath: '/services/boarding-schools'
      preLoaderRoute: typeof ServicesBoardingSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/athletic-recruitment': {
      id: '/services/athletic-recruitment'
      path: '/services/athletic-recruitment'
      fullPath: '/services/athletic-recruitment'
      preLoaderRoute: typeof ServicesAthleticRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesAthleticRecruitmentRoute: ServicesAthleticRecruitmentRoute,
  ServicesBoardingSchoolsRoute: ServicesBoardingSchoolsRoute,
  ServicesUndergraduateRoute: ServicesUndergraduateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
